### ISSUE TITLE
Unexpected Close Tag Bug with Antlers

### ISSUE THREAD

**Issue by jcohlmeyer** [alexanderweiss/nova-prettier#10]
[Antlers](https://docs.statamic.com/antlers) is the templating language used by [Statamic](https://statamic.com).

When using antlers prettier incorrectly shows the following error:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/1778271/89887365-1e6c0c00-db9c-11ea-8b72-918d6d3029a2.png">

**Comment by alexanderweiss** [comment]
I don't think Prettier supports Antlers? You can disable automatic formatting on save for the whole project in the project settings. Or you can use a `.prettierignore` file (see https://prettier.io/docs/en/ignore.html).

**Comment by jcohlmeyer** [comment]
That is unfortunate as I do a lot of work with antlers.
