### ISSUE TITLE
Weird line separation

### ISSUE THREAD

**Issue by dragoonDorise** [alexanderweiss/nova-prettier#11]
This:

` <span class="h1">Apple Marina Bay Sands abre el jueves en Singapur</span>`

Get converted to:

`           <span class="h1"`
           
 `>Apple Marina Bay Sands abre el jueves en Singapur</span`
         ` >`

**Comment by alexanderweiss** [comment]
Is this in a HTML file with a .html extension? And does the prettier playground (with the same config) (https://prettier.io/playground/) format it the same way?

**Comment by dragoonDorise** [comment]
It the playground works fine.

Here is the full html code:

`<html
  class="no-legacy-ie no-js"
  lang="es"
  itemscope
  itemtype="http://schema.org/Organization"
>
  <module href="/components/_layout/_head.html"> </module>
  <body>
    <div class="wrapper">
      <main class="main">
        <div class="container-grid">
          <span class="h1">Apple Marina Bay Sands abre el jueves en Singapur</span>
          <p>
            Singapur — Apple ha mostrado hoy un avance de Apple Marina Bay
            Sands, la primera Apple Store construida directamente sobre el agua.
            La tienda, que emerge en forma de esfera flotante de las relucientes
            aguas de Marina Bay, es una nueva y cautivadora manera de visitar
            uno de los lugares más reconocibles de Singapur.
          </p>
        </div>
      </main>
    </div>
    <script defer src="../components/_app-frontend/_app-frontend.js"></script>
  </body>
</html>
`

**Comment by alexanderweiss** [comment]
It seems to be a problem with Prettier's HTML parser. If you set the playground to [use the HTML parser](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UABMagEYQAmAnoSaWVQJYBuxYOAhgM48C8BEAHcATlwAOEuKKH1GjVFi7MSnXgKHLVcogoWoW7dX0HhoMFVBkBaAOajmVXQ32KeErmu6mh6AIxyAIJSOHDEALJcjlBcxABCXDTEAMpeVDzEXOSi4XA4xABWAK5wrHCZCKmqdpLFoqgA9B5e8m5kjUZtBo3aUN0dXXodlLT0TZi49CAANCAQEjDM0DzIoNGiEMIACtEIqyhcOMJJq3M5XGAA1nAwKZ5gNcgwoqVzcFjkcFRU3wAyXjsxS4djgADEIKJlDAllA7MgQFxijAILMQJMcAB1dDMeAtMBwFL7XFsXE0BFgPho1Q8GQwbbiOzKZAAMyOtLmhR4AA94uJrrc0lg4H9VHBWey4JyeSkamEAIrFCDwCU4DkgTyiWmiBEYtESGIwTFOGDoZAADgADHMDRBaZjxBIEQaKjJymiAI5K+AMhYHRE8GzWb7fNG5L3MXIMkHMpBstVSkC0rDMZ6vRM8OVwRXK8VxyVzSzkY1UU3IABMhfEzBwNQAwhAsLGQBUAKxo4q0gAq2QO8fVrFKAEkoL9YCkwI5FkFRykYDQwqraQBfZdAA) you get the same strange line break behaviour. Prettier in the extension automatically decides to use the HTML parser based on the file extension. Maybe check out the Prettier repo's issues or create one.
