### ISSUE TITLE
The extension “Prettier” has stopped responding

### ISSUE THREAD

**Issue by elemis** [alexanderweiss/nova-prettier#13]
I keep getting the error: "The extension “Prettier” has stopped responding."
Happens every time I save a document or click "Format with Prettier"
The extension simply doesn't work properly on my end. 
Any suggestions?

**Comment by alexanderweiss** [comment]
Could you check the extension console to see if there's any output there? You might need to have it open before saving the file for the output to show up. Also, how large / how many lines is the file?

**Comment by elemis** [comment]
Thank you for getting back to me @alexanderweiss 
Sorry but I can't seem to locate extension console. Where is it located exactly?

**Comment by elemis** [comment]
@alexanderweiss 
I only get this line in console:
"Using prettier from /Users/.../node_modules/prettier (extension located at: /Users/.../Library/Application Support/Nova/Extensions/alexanderweiss.prettier)"

**Comment by alexanderweiss** [comment]
It seems like Prettier is actually just really slow in some cases. It might be specifically because it's running in Nova. I'll look into this a little more.

**Comment by radogado** [comment]
Getting this error often. Thanks for looking into it.

**Comment by alexanderweiss** [comment]
It seems to be the 'standalone' version of Prettier that's the problem. There will be a new update with an experimental option to use the normal version of Prettier instead. I'll let you know when it's out. It would be great if you could test it @elemis  & @radogado.

**Comment by alexanderweiss** [comment]
Okay. A little quicker than planned. There's a new version out with a `Run Prettier in a separate process (experimental)` option that is a lot faster on large files in my testing. Could you enable that in the preferences in the Extension Library, test it out and let me know how it works for you @elemis & @radogado?

**Comment by elemis** [comment]
@alexanderweiss Tested the latest version with the said option, I no longer get the error but nothing happens. No formatting being done on the files. No message on the console either.

**Comment by alexanderweiss** [comment]
What files? Any file, or just PHP files? Did you install Prettier and the php plugin in your repo? (`npm install prettier @prettier/plugin-php`). The PHP plugin isn't included with the bundled Prettier. The extension console will say it's 'Loading project prettier' if it's detected Prettier in your project.

**Comment by elemis** [comment]
Mine are HTML files. I installed Prettier. I see "Loading project prettier at..." and "Starting Prettier service" logs in the console and nothing else.

**Comment by alexanderweiss** [comment]
Okay. I have seen Prettier basically choke on some more complex though not necessarily long files. (The Prettier function that remembers your cursor position can be a lot slower than the normal one) And when running Prettier in a separate process it doesn't currently detect that it's really slow. To make sure it's not a problem in general: does it work with smaller/simpler files? And do you happen to have a shareable file where this problem occurs?

Thanks for the continued help trying to figure this out 😁

**Comment by elemis** [comment]
Thanks for helping me :) 

Prettier works fine with files with a few lines of code. Tried with bunch of different Bootstrap example files. Worked properly with less than 10KB size documents. But started failing on larger ones. For example this HTML file didn't work: https://v5.getbootstrap.com/docs/5.0/examples/carousel/ even though it's just 11KB.
Restarting Nova and trying again didn't help.

The thing is the files I normally work with are larger than the Bootstrap examples. Not sure if I would call them complex though?

**Comment by alexanderweiss** [comment]
Thanks for that file! It's really helpful. I'm currently looking at ways to speed it up. I'll keep you posted.

**Comment by alexanderweiss** [comment]
I've uploaded a prerelease version to Github that contains a ton of improvements, including a huge speed improvement for me at least. It'd be great if you could try it! You can download it here: https://github.com/alexanderweiss/nova-prettier/releases/download/1.6.0/prettier.novaextension.zip, then just double-click it to install (and make sure you have the `Run Prettier in a separate process (experimental)` preference enabled.

**Comment by elemis** [comment]
Okay just tried the beta. It takes some time to prettify the documents but it works. 

Though I don't see "Run Prettier in a separate process (experimental)" setting anymore so I couldn't enable it. But there is "use compatibility mode" setting, and if I select it then it fails to work again and I start getting the  "The extension “Prettier” has stopped responding." error. 

Long story short: If "compatibility setting" is disabled Prettier works properly on my end but is a bit slow (v1.6.0-b2)

**Comment by alexanderweiss** [comment]
That sounds promising! Is that on the example file you shared? How slow is it? I'm not sure if I can make it faster than this without losing your cursor position... Do you use Prettier in another editor? Is it faster for you?

The experimental mode is the default in 1.6.0, so that makes sense!

**Comment by elemis** [comment]
I see. Could keeping the cursor position be an option then? :) if that would help making it faster? Not sure if it would even be possible but thought I should ask.

Tried with my own HTML files by the way. They are longer than the example file. The example file was a bit faster.

I haven't tried Prettier on a different editor until now. Thought I was :) Apparently I've been using Beautify on Atom, not Prettier, which is so fast, so I was expecting the same performance. Sorry for not checking earlier. Just tried Prettier there too, and it was dead slow and also returned an error. Even with the example file. At least we have a working version of Prettier on Nova now :)

**Comment by alexanderweiss** [comment]
Yes. Do you think this should be per-file? So basically, if the first time it's slow it'll not try to keep the cursor position the next time (or ask if you'd like to not do it)? Or just a generic setting for files larger than X? Can you maybe check how many seconds it takes (more or less). That would help with adding such a feature.

Also, it's probably faster on subsequent saves right (when it doesn't change as much)?

No problem! I needed to try things out to realise that too haha.

**Comment by elemis** [comment]
Could be a generic setting. Honestly I don't really care for the cursor position :)

6 seconds with the 12KB example Bootstrap file (226 lines).
16 seconds with an 35KB HTML file (618 lines).
23 seconds with an 45KB HTML file (1544 lines) -- threw the error in between, I chose "wait" and then it finished the formatting properly.

Subsequent formattings are faster, right.

Hope this helps.

**Comment by alexanderweiss** [comment]
It's really annoying when you're editing a file and your cursor suddenly moves to a different position when you save ;)
But that helps! I'll look into it.

**Comment by alexanderweiss** [comment]
I think it's working pretty well for most people and finding out if restoring cursor position will be slow is not easy, so I'm closing this for now.
