### ISSUE TITLE
Failed to resolve Prettier configuration

### ISSUE THREAD

**Issue by manuzoli** [alexanderweiss/nova-prettier#14]
Whenever I want to save a file i get the error, that the Prettier configuration can't be resolved. 
I am working remotely via SFTP and FTP. I tried on different computers. 

Prettier v1.2.0 on Nova 202519

![image](https://user-images.githubusercontent.com/8931133/93447433-b1ead800-f8d2-11ea-8b5c-1ce0738e5fb1.png)

**Comment by catswithbenefits** [comment]
I have the same issue with the same software versions.

**Comment by alexanderweiss** [comment]
Are you also working on remote files @catswithbenefits?
And could you open the extension console and share the output that's there @manuzoli ?

**Comment by catswithbenefits** [comment]
Yes, I am working remote.

How to open the extension console?

**Comment by charger3444** [comment]
I have same problem, but with php with remote files:

<img width="642" alt="Schermata 2020-09-16 alle 21 56 24" src="https://user-images.githubusercontent.com/71442677/93468475-511dc880-f8ef-11ea-9920-372651a1d02d.png">

**Comment by manuzoli** [comment]
The Output is:
_Unable to get config for /var/www/clients/client961/web1525/web/fileadmin/covid.json: Error: Arguments must all be strings_

**Comment by alexanderweiss** [comment]
I haven't been able to reproduce this yet.

@catswithbenefits You can open the console through Extensions > Show extension console

@manuzoli Do you have prettier installed in your project folder? And if so, what version?

**Comment by alexanderweiss** [comment]
@manuzoli, there's a new version of the extension v1.2.1 that should include stack traces with errors. Could you possibly share those?

**Comment by zpv** [comment]
> @catswithbenefits You can open the console through Extensions > Show extension console

Additionally, make sure you have Extension Development enabled in Prefererences > General

**Comment by manuzoli** [comment]
I am now using the newest 1.2.1 release. 

It now says: 

Using prettier from /Users/zoli1/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier (extension located at: /Users/zoli1/Library/Application Support/Nova/Extensions/alexanderweiss.prettier)

Unable to get config for /var/www/clients/client179/web205/web/webcam/converter.php: Error: Arguments must all be strings

i don't really see a stacktrace i think.

**Comment by subdigital** [comment]
I have the same issue. Extension Console shows:

> Prettier[9:46:33.697000] Unable to get config for /Volumes/Macintosh HD/Users/ben/projects/myapp/.gitignore: Error: Arguments must all be strings

I'm editing local files.

**Comment by alexanderweiss** [comment]
I think I've been able to reproduce the problem and it should be fixed in the latest release (v1.3.0). If not, the stack trace should now actually be included in the log output @manuzoli.

**Comment by manuzoli** [comment]
It works now. Thank you very much!!!!!!
