### ISSUE TITLE
Error: No parser could be inferred for file:

### ISSUE THREAD

**Issue by charger3444** [alexanderweiss/nova-prettier#17]
Hi, on remote project I've got:

Error: No parser could be inferred for file: /[domain_name]/public_html/application/controllers/Cerca.php yr
normalize@file:///Users/carlo/Library/Application%20Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/standalone.js:15:100808
formatWithCursor@file:///Users/carlo/Library/Application%20Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/standalone.js:15:114671
file:///Users/carlo/Library/Application%20Support/Nova/Extensions/alexanderweiss.prettier/Scripts/main.js:281:71
[native code]
Promise@[native code]
[native code]
file:///Users/carlo/Library/Application%20Support/Nova/Extensions/alexanderweiss.prettier/Scripts/main.js:277:20
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]

**Comment by alexanderweiss** [comment]
It shouldn't actually try to format PHP files as there's no formatter available for PHP. Is the `Format with Prettier` command enabled for php files / this file for you? And is the syntax (shown in the bottom right corner of the window) set to something other than php?

**Comment by charger3444** [comment]
> It shouldn't actually try to format PHP files as there's no formatter available for PHP. Is the `Format with Prettier` command enabled for php files / this file for you? And is the syntax (shown in the bottom right corner of the window) set to something other than php?

Yes it is enabled, and syntax is set to Php-Html.

Should be really helpful to have prettier with php for remote project

**Comment by alexanderweiss** [comment]
The latest update (v1.4.0) will now use the HTML parser for your PHP files, so it should format the HTML in them properly. Full PHP support using the plugin is a little more involved (https://github.com/alexanderweiss/nova-prettier/issues/3), but I'll look into it too. Thanks for reporting this! And let me know if you run into any other issues.

**Comment by charger3444** [comment]
> The latest update (v1.4.0) will now use the HTML parser for your PHP files, so it should format the HTML in them properly. Full PHP support using the plugin is a little more involved (#3), but I'll look into it too. Thanks for reporting this! And let me know if you run into any other issues.

Thanks, but I must disabled extension cause code after formatting is completely messy (php-html syntax).
Really missing php support...

**Comment by alexanderweiss** [comment]
Sorry about that. The results seemed pretty good in my testing. If you go to the project settings there's an 'Environment' group in the left column. Prettier should be under there (if you have it turned on). Alternatively you can also turn off format on save by going to the 'Preferences' tab of the extension in the Extension browser.

I have a development version that now supports plugins, but it's a little rough still. I think it should be out in the coming days. I'll share it pretty soon — it'd be great if you could try it out. And I'll close this in favour of #3.

**Comment by GwynethLlewelyn** [comment]
Sorry to leave here a comment, but, you know, Google sometimes still finds this closed answer... :-)

As far as I can see, the latest version I've got for this extension ([v2.3.0](https://github.com/alexanderweiss/nova-prettier/releases/tag/v2.3.0)) _does_ support external plugins, and you can get a plugin for PHP with `npm install @prettier/plugin-php`, which is sort-of-official-but-not-included-with-prettier-by-default, and supports reasonably recent versions of PHP (there _might_ be a few issues with 8+).

It works well for me :-)
