### ISSUE TITLE
prettier in Nova always formats files even when setting is switched off

### ISSUE THREAD

**Issue by garethlewis** [alexanderweiss/nova-prettier#18]
I have disabled running prettier on saving a file in the project settings, but when I create a new file and save, prettier automatically formats that file.  This is true for any new file.  If I go to the project settings and toggle the check box, this stops prettier formatting the new file.  Any chance this can be solved in an update.

**Comment by alexanderweiss** [comment]
That's a bug. Thanks for letting me know. I'll look into fixing it very soon.

**Comment by alexanderweiss** [comment]
This is fixed in the latest release (v1.4.0). Let me know if you have any more issues with it! Thanks for helping out :)
