### ISSUE TITLE
Modify only dirty parts of the file?

### ISSUE THREAD

**Issue by michalsapka** [alexanderweiss/nova-prettier#2]
Would it be possible to format only parts of the file that were modified? Most people in my org don' use prettier, so the script will change their code.

**Comment by alexanderweiss** [comment]
How would you like this to work exactly? Format only the selected text? Or do you mean using `.prettierignore` to not format certain files? I think the latter definitely makes sense.

**Comment by alexanderweiss** [comment]
The latest version now contains support for `.prettierignore`. I'll close this issue, but if that's not what you were looking for let me know!
