### ISSUE TITLE
How can I change the default Tabwidth value ?

### ISSUE THREAD

**Issue by gomathieu** [alexanderweiss/nova-prettier#20]
The default value is actually 2, but I need it to be 4.

In index.js and doc.js of node_module, I can find this :

tabWidth: {
	type: 'int',
	category: CATEGORY_GLOBAL,
	default: 2,
	description: 'Number of spaces per indentation level.',
	range: {
		start: 0,
		end: Infinity,
		step: 1,
	},
},

I tried changing it to 4, but is doesn't seem to be working.

**Comment by alexanderweiss** [comment]
You can just add a Prettier configuration file in a parent folder of the file you're editing as you would do when using Prettier directly: https://prettier.io/docs/en/configuration.html

**Comment by alexanderweiss** [comment]
I added a note about this to the readme. Let me know if you run into any issues 😃!
