### ISSUE TITLE
Uncaught exception when opening a project

### ISSUE THREAD

**Issue by dmcgrew** [alexanderweiss/nova-prettier#23]
Not sure what is causing this. I tried the experimental preference and that doesn't seem to make a difference. This error is in the console as soon as I open a project.

Prettier[16:12:40.098000] Extension encountered an uncaught exception:
/Users/designer1/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/main.js (Line 328, Column 0)
SyntaxError: Unexpected token '?'

**Comment by alexanderweiss** [comment]
Thanks for the report! This problem I contacted Panic about, but haven't heard back.

**Comment by alexanderweiss** [comment]
So, this appears to be caused by some macOS versions not supporting not supporting some newer JS syntax. I've just released v1.5.2 of the extension that should fix it. I wasn't able to test on older macOS yet though, so if you run into any other issue like this, let me know!
