### ISSUE TITLE
Error while formatting on save

### ISSUE THREAD

**Issue by sgkul2000** [alexanderweiss/nova-prettier#25]
# Prettier fails to format on save
I have a python code and every time I save it I get a message in the upper right corner which says that format on save failed.
the following screenshot is the error message that I get.
but the thing is prettier is able to format when I use keyboard shortcut.
**so its a format on save issue**

<img width="318" alt="Screenshot 2020-10-04 at 8 21 27 PM" src="https://user-images.githubusercontent.com/47442612/95018754-4c8f3900-067f-11eb-8b76-b6940c4871f5.png">

**Comment by alexanderweiss** [comment]
Thanks for reporting this! This happens when Prettier doesn't support the language you're trying to format (like Python). You're not getting it when you use the keyboard shortcut because it doesn't even try to format it. This will be fixed in the next release — it won't bug you about it anymore.

**Comment by sgkul2000** [comment]
Than you for the quick response. Good to know that nova extension development of Prettier is so active.
Have a great day!!
