### ISSUE TITLE
.editorconfig and prettier

### ISSUE THREAD

**Issue by thfrlw** [alexanderweiss/nova-prettier#27]
Hey, I was just wondering if I have .editorconfig set to use tabs, shouldn't prettier change spaces to tabs on save ?

**Comment by alexanderweiss** [comment]
Prettier does indeed have an option for that. I've enabled it now and I'll make sure to get it out in a release soon.

**Comment by thfrlw** [comment]
Thanks You for that. Glad its a little change :)

**Comment by alexanderweiss** [comment]
The latest release has it enabled.
