### ISSUE TITLE
PHP support

### ISSUE THREAD

**Issue by bugcafe** [alexanderweiss/nova-prettier#3]
Is there a way to add PHP support to this extension?

**Comment by alexanderweiss** [comment]
Oh! I didn't know about plugins. I'll look into supporting your local Prettier install (https://github.com/alexanderweiss/nova-prettier/issues/6) so that should automatically make the plugins work.

**Comment by alexanderweiss** [comment]
Turns out this is a little more complex than I'd hoped. Not all plugins can't be used with standalone Prettier. So it'll probably need to run in a separate process, making things a little more complex.

**Comment by saltnpixels** [comment]
I also was looking for this.

**Comment by alexanderweiss** [comment]
The latest update (v1.5.0) has experimental support for plugins. You just need to enable the `Run Prettier in a separate process (experimental)` option in the preferences in the Extension Library and Prettier and the plugins need to be installed in your project. It would be awesome if you could test it out and let me know how it works @bugcafe & @saltnpixels!
