### ISSUE TITLE
Error when formatting

### ISSUE THREAD

**Issue by Corcules** [alexanderweiss/nova-prettier#30]
Wehndoing formatting, on saving file or manually, i get an error "Unable to get config..."
![Capture d’écran 2020-10-08 à 12 50 56](https://user-images.githubusercontent.com/24244917/95449478-23172b80-0965-11eb-9c3a-c445cd7638d7.png)

**Comment by alexanderweiss** [comment]
What version of node do you have installed? And do you use nvm? If so, what's the non-nvm version of node? It seems it's a little older and some syntax is unsupported. If I know what you're running I can see if I can improve it or add a warning.

**Comment by Corcules** [comment]
Well done, sorry for that my node and npm versions were old. I update all and houra, prettier runs in Nova well... SO COOL ! 

Maybe you should add some prerequisites in the readme :
- node minimal version
- npm minimal version
- xcrun (Xcode Developer Command line Tools)

**Comment by alexanderweiss** [comment]
Yes, I'll add them soon. Thanks for the help!
