### ISSUE TITLE
Only formatting JS files.

### ISSUE THREAD

**Issue by akmcbroom** [alexanderweiss/nova-prettier#31]
When connecting to a project via FTP, and formatting, it is only working for the JS files.

Also not able to set any settings, like tab width, etc. It is not clear on how set this up for remote projects.

**Comment by alexanderweiss** [comment]
It works on non-JS files for remote projects for me.

As to the configuration. Yes... That's a problem. Do you have any preferred way of how you'd configure that?

**Comment by akmcbroom** [comment]
Within the plug-in preferences UI?

**Comment by alexanderweiss** [comment]
Just a text field to put the `.prettierrc` contents?

Also, do you have any more info on what exactly isn't working / how to reproduce the issue?

**Comment by alexanderweiss** [comment]
The latest release (v1.8.0) now allows you to set the default Prettier configuration options in the extension preferences. You can also set the at the project level.
