### ISSUE TITLE
Modifies PHP files - which it shouldn't

### ISSUE THREAD

**Issue by Borlabs-Ben** [alexanderweiss/nova-prettier#38]
Prettier shouldn't modify php files, but it does.

I added a .prettierignore file into the root of my Nova project with this content
```
build
coverage

*.php
```

but prettier ignores it.

**Comment by Borlabs-Ben** [comment]
Disabling and re-enabling the plugin doesn't work. PHP files are always modified on save.

**Comment by alexanderweiss** [comment]
That should work. Are you editing remote files? `.prettierrc` doesn't currently work for remote files. You can also disable format on save for PHP across projects in the extension preferences in the Extension Library.

**Comment by Borlabs-Ben** [comment]
No I don't work with remote files, but disabling PHP in the extension preferences works for me, thank you!

**Comment by alexanderweiss** [comment]
In that case I'll just close this 👍

**Comment by muuvmuuv** [comment]
Disabling PHP in the extension settings no longer works :/
