### ISSUE TITLE
Prettier config via prettierrc in project root ignored.

### ISSUE THREAD

**Issue by vichudson1** [alexanderweiss/nova-prettier#39]
I have the following in a .prettierrc file in my project's root folder, but it never seems to be used. I've tried relaunching Nova several times without any luck. I'm fully willing to admit I'm new to Nova and Prettier so if I've missed anything feel free to point that out.

Im using the prettier version bundled with extension version 1.7.1.

.prettierrc content
`{ "tabWidth": 4, "useTabs": true }`

Answering your questions from the other thread.

@vichudson1 Are you editing local or remote files? It doesn't currently work with remote files.
Local files

If you're editing local files, can you share the logs from the extension console (first enable extension development in Nova preferences), 
```
Prettier[14:30:25.225000] Loading bundled prettier at /Users/victor/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier

Prettier[14:30:26.367000] Starting Prettier service

Prettier[14:30:36.271000] Formatting /Volumes/Macintosh HD/Users/victor/Sites/empire/layouts/episode/audio/player.html

Prettier[14:30:36.558000] Applying formatted changes to /Volumes/Macintosh HD/Users/victor/Sites/empire/layouts/episode/audio/player.html
```

where your .prettierrc is located, 
It is in the root of my project. Following the path from the console above the folder is empire.

and whether Comptability mode is enabled in the extension's preferences (in the extension library)? 
Compatibility mode is off.

Also, maybe create a separate issue so we don't annoy Gregg 😃.
Sorry about that, Didn't think about Gregg and commented on what I thought was a relevant issue. 😉 

You're more than welcome to look at my [prettierrc file in my project](https://github.com/vichudson1/empire/blob/develop/.prettierrc).

Thanks for your help and the great extension.

**Comment by alexanderweiss** [comment]
I haven't been able to reproduce it. It does work for me. Have you tried closing and reopening the file after formatting? Nova doesn't change the tab displayed tab width when all the spaces are replaced by tabs.

**Comment by vichudson1** [comment]
I have not tried closing and reopening the file. I did go and use the arrow keys to move the cursor. That showed the original number of tabs. I’ll try that later. Thanks. 

Vic Hudson

**Comment by vichudson1** [comment]
Can you confirm for me my prettierrc file is correct and in the right place?

Vic Hudson

**Comment by alexanderweiss** [comment]
I think having both `tabWidth` and `useTabs: true` might actually the problem. That makes sense: can't have X tab width when you use tabs.

**Comment by vichudson1** [comment]
That did in fact turn out to be the case. I got rid of tabWidth and it started working. I then toggled usedTabs a few times, restarting Nova in between, just to make sure my config file was working and it is. Thanks for your help.

**Comment by alexanderweiss** [comment]
Perfect!
