### ISSUE TITLE
Commonly used format options in extension preference pane

### ISSUE THREAD

**Issue by vichudson1** [alexanderweiss/nova-prettier#40]
It would be nice to have some commonly used format options configurable in the extension's preferences and maybe even per project. I'm thinking things like tabs vs spaces and tab width, etc.

**Comment by alexanderweiss** [comment]
Yes, I agree. It's actually required for remote files to work properly. See #37 and #31. I'm currently working on this.

**Comment by alexanderweiss** [comment]
The latest release (v1.8.0) now allows you to set the default Prettier configuration options in the extension preferences. You can also set them at the project level.
