### ISSUE TITLE
No Result (ignored or no parser)

### ISSUE THREAD

**Issue by highree** [alexanderweiss/nova-prettier#42]
Hi Alex, 

after the last patch with the possibility to configure prettier in the extension, it seems my html.erb files aren't getting formatted. Is this only me? or anyone else experience same problem. 

Prettier[15:44:03.557000] No result (ignored or no parser) for /.../index.html.erb

**Comment by alexanderweiss** [comment]
Do you have overrides configured to make erb files work? Do you happen to know in which version it last worked? Prettier doesn't appear to support erb files by default, so unless you set up an override I don't think it should get formatted.

**Comment by highree** [comment]
hi Alex, 

i see, I have a mixed project with html and erb files. And I didnt knew that erb files not working. Is there a ways to treat erb files as html files ?

**Comment by alexanderweiss** [comment]
You can set the `parser` option in an override in your Prettier configuration file: https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option
