### ISSUE TITLE
Please add Twig support

### ISSUE THREAD

**Issue by Tekl** [alexanderweiss/nova-prettier#44]
There's already a Twig plugin for Prettier:

https://github.com/trivago/prettier-plugin-twig-melody

**Comment by kimili** [comment]
I'm trying to run this as a plugin with the prettier extension, however, it throws an error when trying to reformat a twig file. The error is:

```
Prettier[12:50:41.112000] TypeError: undefined is not an object (evaluating 'error.message.match') issuesFromPrettierError@file:///Users/michael/Library/Application%20Support/Nova/Extensions/alexanderweiss.prettier/Scripts/main.js:1191:31
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
promiseReactionJob@[native code]
```

[Here's the line it's complaining about](https://github.com/alexanderweiss/nova-prettier/blob/master/prettier.novaextension/Scripts/main.js#L1191).

To set this up, I've created a `project.json` file in my project root including the following:

```json
{
  "dependencies": {},
  "devDependencies": {
    "prettier": "^2.1.2",
    "prettier-plugin-twig-melody": "^0.4.6"
  }
}
```

And my `.prettierrc.json` file at the project root looks like this:

```json
{
  "singleQuote": true,
  "printWidth": 120,
  "plugins": ["./node_modules/prettier-plugin-twig-melody"]
}
```

I believe I've set this up correctly to run the twig extension with the prettier plugin, but here we are.

**Comment by alexanderweiss** [comment]
Yes, you can use the Twig plugin by installing Prettier and the Twig plugin in your project. You shouldn't normally need to explicitly add the plugin to your `.prettierrc`, Prettier will generally find it automatically.

It seems like there's an issue with parsing the (syntax) errors when that plugin is used though. I'll look into it.

**Comment by alexanderweiss** [comment]
I've fixed the syntax error parsing issues for that Twig plugin in v1.8.1 which I just released @kimili. Let me know if you're still having trouble with it.

**Comment by kimili** [comment]
Thanks for the quick patch, @alexanderweiss! I tried to trip it up after updating the plugin, and I could not do so. I think we're good with this issue.

As an aside, the only error I was able to trigger was a parsing error in the `prettier-plugin-twig-melody` plugin, which Nova notified me of, and for which there's [an open issue](https://github.com/trivago/prettier-plugin-twig-melody/issues/60).

![Screen Shot 2020-10-24 at 08 44 50](https://user-images.githubusercontent.com/351819/97082104-310bb400-15d5-11eb-8190-937faf45a8b7.png)

Thanks!

**Comment by alexanderweiss** [comment]
Oh! There can be two `^` signs. Interesting. I'll make sure that'll also be shown as a syntax error in Nova.

**Comment by Tekl** [comment]
Where do I have to install the plug-in? Most times I don't work with projects.

**Comment by alexanderweiss** [comment]
@Tekl, currently using plugins is only properly supported when you install Prettier in your project or whatever folder you have open in Nova. You can hack your way around it by going to `~/Application Support/Nova/Extensions/alexanderweiss.prettier` and use `npm` in that folder to install whatever plugin you want.

Do you use Prettier with other editors? How do you do it there?

**Comment by Tekl** [comment]
Thanks four your help. It seems that you mean: `~/Library/Application Support/Nova/Extensions/alexanderweiss.prettier`. After dealing with dependencies (melody-idom and melody-runtime) I now can prettify my twig files. Thanks for you help.

I haven't used Prettier before Nova as I don't needed it. In VSCode I just installed the appropriate extensions and it worked.
