### ISSUE TITLE
Question about resaving the file after formatting

### ISSUE THREAD

**Issue by biati-digital** [alexanderweiss/nova-prettier#47]
Hi @alexanderweiss, I had the same problem as you with one of my extensions where after formatting, the file would end up in a constant state of not saved so i had to do the same as here https://github.com/alexanderweiss/nova-prettier/blob/7e43944b0a01781550412599e55ada14107a9ae6/src/Scripts/formatter.js#L206

With Nova 2, i've noticed that (at leats for the tests i did) it's no longer required to resave the file, Nova will save the file correctly after the formatting is done. Have you noticed the same with your extension?

**Comment by alexanderweiss** [comment]
I haven't tested, but I heard from Panic that they were working on it and it's listed in the release notes (the item mentioning onWillSave and async) as fixed. So I would assume it works now. I'll probably remove the hack in the near future.

**Comment by biati-digital** [comment]
Great, then i think it's fixed, i'll remove the hack from my extension then, it's really annoying when editing remote files.
