### ISSUE TITLE
Use single quote does not work

### ISSUE THREAD

**Issue by biati-digital** [alexanderweiss/nova-prettier#48]
Setting "Use single quotes" in the extension preferences does not work, it will always use double quotes, the same for "Use semicolons" 

If i use a .prettierrc.json it works correctly

**Comment by alexanderweiss** [comment]
Do you have a Prettier configuration file in your project (without these settings in there)? If you do, the formatting settings in the extension preferences are ignored and you need to configure everything in the configuration file.

If not, have you configured this in the global extension preferences or in the project extension preferences? I can't seem to reproduce it.

**Comment by biati-digital** [comment]
Hi @alexanderweiss 

1.- There was no prettier config in the project, i created the file after testing the extension preferences because it was not working

![Screen Shot 2020-11-02 at 17 10 10](https://user-images.githubusercontent.com/1219228/97929213-46e44c00-1d2e-11eb-90ab-bd8c6756f67a.png)


2.- I've not changed anything in the project extension preferences, everything is set to Global Default.

![Screen Shot 2020-11-02 at 17 09 14](https://user-images.githubusercontent.com/1219228/97929154-2916e700-1d2e-11eb-8ae3-cfe0d69e2470.png)

I prefer to use single quotes, i've configured Eslint to error double quotes but once i save the file Prettier changes the single quotes to double quotes and also ignores the "Use semicolons" 

![Screen Shot 2020-11-02 at 17 12 10](https://user-images.githubusercontent.com/1219228/97929336-8e6ad800-1d2e-11eb-99ca-b95122a401ca.png)


Prettier is the only formatter i've that formats on save, Eslint is configured to not touch the files only show errors. If i add the .prettierrc.json it works correctly

I tried to enable logging to see exactly what was happening but there's no infor about what config is using.

**Comment by biati-digital** [comment]
I've tried configuring the project extension preferences but still the only way it works correctly is using a .prettierrc.json file

**Comment by alexanderweiss** [comment]
Yeah, the source of the configuration isn't currently logged. Do you have compatibility mode enabled? And/or is there a Prettier configuration file in some parent directory of your project folder?

**Comment by biati-digital** [comment]
Ahhhhh i found a prettier config file waaaay up in a parent directory, i removed this file and everything seems to work correctly now. Is this the way it's supposed to work the extension? anyway, thank's for the help.

**Comment by alexanderweiss** [comment]
That's Prettier's built-in config resolution picking it up. And the extension doesn't apply the preferences if Prettier finds a config file (otherwise configuration shared in a repo might not get applied the same for everyone). So it's confusing but expected behaviour.
