### ISSUE TITLE
Code folding results into breaking the code when Prettier is active

### ISSUE THREAD

**Issue by Borlabs-Ben** [alexanderweiss/nova-prettier#50]
See the video: https://www.dropbox.com/s/5782rvsv0u7q5k5/2020-11-03_16-49-30-2.mp4?dl=0

**Comment by alexanderweiss** [comment]
Thanks for reporting that and for the video! I tried to reproduce your error but I couldn't. I did run into some strange Nova code folding bugs though... Could you try and remove as much as possible from the file (but it still happens) and share that.

**Comment by alexanderweiss** [comment]
Hey @Borlabs-Ben! Can I ask why you closed this? Is it a not a problem with the Prettier extension?

**Comment by Borlabs-Ben** [comment]
I'm not able to reduce the code so much that the bug is triggered.

**Comment by alexanderweiss** [comment]
Any chance you can share the file? Or part of the file (where it still happens)? I would really like to fix it.

**Comment by Borlabs-Ben** [comment]
I'm unable to reproduce the bug with the current file. I will keep an eye on it and come back, when the bug re-occurs.

**Comment by alexanderweiss** [comment]
Aha. Good and bad I guess. Please do 😃!
