### ISSUE TITLE
Bundled prettier being used instead of project prettier

### ISSUE THREAD

**Issue by jonathanpike** [alexanderweiss/nova-prettier#51]
Hi,

First of all, thank you for this wonderful extension.  It generally works great.  I'd like to be able to use it with the [ruby plugin](https://github.com/prettier/plugin-ruby) (since my project is a Rails project), but it seems that the plugin can't find the project's version of prettier, and therefore (I assume) can't access the installed plugin. 

I looked at the source and it looks like you're running `npm ll prettier --parseable --depth 0` to find if prettier is installed for the project.  Running that in my project root finds nothing.  However, the project is using yarn (I'm not sure if that makes a difference) and if I run the mostly equivalent command of `yarn list --depth 0 --pattern prettier`, it finds it.  

Am I doing something wrong here?

**Comment by alexanderweiss** [comment]
Does the `npm ll prettier --parseable --depth 0` output nothing at all?
What versions of npm and yarn do you have (run `npm -v` to check). And is Prettier just installed in `<your-project-root>/node_modules/prettier` or somewhere else?

**Comment by jonathanpike** [comment]
Thanks for the reply.  

I tried `npm ll prettier --parseable --depth 0` again and it actually found the prettier package this time, so I decided to try to restart Nova and see if it would load it instead of the bundled prettier.  When I restarted, it actually loaded the correct prettier.  Then, I re-installed the `plugin-ruby` package, as follows: `yarn add --dev @prettier/plugin-ruby`.  Now, it loads the bundled prettier once again.  

The output of `npm ll prettier --parseable --depth 0` was as follows when it worked: 
```sh
$ npm ll prettier --parseable --depth 0
/Users/jpike/code/ruby/jilt-app/node_modules/prettier:prettier@1.19.1
```

Then, when I installed the plugin, the output is like this: 

```sh
$ npm ll prettier --parseable --depth 0

/Users/jpike/code/ruby/jilt-app/node_modules/prettier:prettier@1.19.1
```

Notice the newline character (probably because of the plugin being found).

**Comment by alexanderweiss** [comment]
Awesome that you've dug into it! NPM has some weird whitespace behaviour it seems. This'll be fixed in the upcoming release. I need to test it a little more extensively because it contains a lot of cleanup, but if you feel like it you can download the prerelease and try it: https://github.com/alexanderweiss/nova-prettier/releases/tag/v2.0.0 Feedback / bug reports are definitely welcome!

**Comment by joshuahamilton** [comment]
Popping in to say that v2.0.0 fixed this problem for me. :)

**Comment by alexanderweiss** [comment]
Great! It's now released 😃

**Comment by jonathanpike** [comment]
@alexanderweiss Thank you _so_ much for dealing with this so quickly!  I can confirm that this is now working for me, too 🎉

**Comment by alexanderweiss** [comment]
Great to hear! Enjoy!
