### ISSUE TITLE
Prettier Extension Adds Unexpected Comman

### ISSUE THREAD

**Issue by jeremy-french-4D** [alexanderweiss/nova-prettier#52]
A comma is added after the last item of an object. The last item should not have a comma.

Given the following  object with 3-properties;

data: {
   A: 1,
   B: 2,
   C: 3
}

Prettier as an unexpected comma after the property "C: 3", producing an unexpected comma:

data: {
   A: 1,
   B: 2,
   C: 3,
![prettier extension on](https://user-images.githubusercontent.com/53099470/99127037-5472bf00-25d5-11eb-842a-a8fea4b10adc.jpg)
![prettier extension off](https://user-images.githubusercontent.com/53099470/99127039-5472bf00-25d5-11eb-8dfa-73a01e3f9c4b.jpg)

}

**Comment by alexanderweiss** [comment]
This is Prettier's default. You can change it using the tailing comma's setting in the project or extension preferences or in a Prettier config file. See also https://prettier.io/docs/en/options.html#trailing-commas

**Comment by jeremy-french-4D** [comment]
Thanks for the quick reply.

In Preferences, changing “Trailing Commas” to “none" works.
