### ISSUE TITLE
Multi-line JSX element closure option doesn't work right.

### ISSUE THREAD

**Issue by DJFriar** [alexanderweiss/nova-prettier#53]
The option for 

> Put the > of a multi-line JSX element at the end of the last line instead of being alone on the next line (does not apply to self closing elements).

does not work. For example if I have `<script src="https://kit.fontawesome.com/abcd1234.js" crossorigin="anonymous"></script>`, no matter what the setting is set to, I end up with:

```
<script
  src="https://kit.fontawesome.com/abcd1234.js"
  crossorigin="anonymous"
></script>
```

When this is set to true the output should be:

```
<script
  src="https://kit.fontawesome.com/abcd1234.js"
  crossorigin="anonymous">
</script>
```

**Comment by alexanderweiss** [comment]
Do you have a Prettier configuration file in your project or any of its parent folders (without these settings in there)? If you do, the formatting settings in the extension preferences are ignored and you need to configure everything in the configuration file.

If not, have you configured this in the global extension preferences or in the project extension preferences?
