### ISSUE TITLE
Does not honor Nova preferences for indents 

### ISSUE THREAD

**Issue by Aduffy** [alexanderweiss/nova-prettier#54]
Preferences set to have indents set using tabs. Prettier over rides that setting and uses spaces. I see Prettier has its own preferences where tabs can be set, but this should automatically mirror Novas prefs where applicable.

**Comment by alexanderweiss** [comment]
This might make sense. Though it might also be a bit annoying as all the other settings are in the extension's preferences. In any case I don't believe it's possible right now because Nova doesn't provide a way for extensions to read the app preferences.

**Comment by fibric** [comment]
@alexanderweiss 
You can ask the TextEditor instance https://docs.nova.app/api-reference/text-editor/#softtabs

It's not perfect because a user can change the setting per file in the bottom right corner. Assuming the setting is unchanged when the user opens a file can help play nicer with tab people.

**Comment by alexanderweiss** [comment]
Yeah. And the text editor will also adapt to the actual file contents, no? It's not necessarily your actual preference. So does it make sense to use? I could make it an option though.

**Comment by fibric** [comment]
According to the API, the `softTabs` and `tabLength` are settable. So the extension preferences can change the TextEditor setting which makes it more consistent.

**Comment by fibric** [comment]
The bad news is that Nova supports `.editorconfig` and if enabled the extension settings would ignore and overwrite the `.editorsetting`

**Comment by alexanderweiss** [comment]
> According to the API, the softTabs and tabLength are settable. So the extension preferences can change the TextEditor setting which makes it more consistent.
So would you want the extension to set these when formatting a file? I'm not sure about reading from them. And doing both doesn't really work of course.

> The bad news is that Nova supports .editorconfig and if enabled the extension settings would ignore and overwrite the .editorsetting
The extension also supports `.editorconfig` files, so I'm not sure what the problem would be here?

**Comment by alexanderweiss** [comment]
I'm closing this because it seems to be fixable with `.editorconfig`. Let me know if you see a good alternative :)
