### ISSUE TITLE
Extension only seems to load bundled prettier

### ISSUE THREAD

**Issue by johngrasty** [alexanderweiss/nova-prettier#55]
I had this issue on Nova 3 and 3.1. nova-prettier is at version 2.

Only the bundled prettier loads according to the console. 

```
Loading bundled prettier at /Users/johnpgrasty/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier
```

`npm ll prettier --parseable --depth 0` in the root of the project shows that prettier is installed in the project.

**Comment by alexanderweiss** [comment]
Hmmm. Can you share the exact output of `npm ll prettier --parseable --depth 0` when run in your project's root?

**Comment by johngrasty** [comment]
Here's the command and output:

```
> npm ll prettier --parseable --depth 0
/Users/johnpgrasty/Desktop/Current/svelte/ggi-svelte-sapper-mdsvex-forestry/node_modules/prettier
```

And just for good measure, here's what the debug console is saying:

```
Prettier[0:46:49.931000] Installing / updating bundled Prettier at /Users/johnpgrasty/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier

Prettier[0:46:51.983000] Loading bundled prettier at /Users/johnpgrasty/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier

Prettier[0:46:51.984000] Starting Prettier service
```

Thanks so much for the great plug-in by the way!

**Comment by alexanderweiss** [comment]
Is that the complete output? What version of `npm` do you have installed? I would expect there to be some extra stuff in addition to the path.

Great to hear 😃!

**Comment by johngrasty** [comment]
Yep. That's it. `npm` is version 7.0.10. `node` is 15.2, and this is on Big Sur (11.0.1). I'll check it on my iMac ASAP which is still on Catalina.

**Comment by alexanderweiss** [comment]
Aha. They've removed the special behaviour of `npm ll` in v7 apparently. I've fixed it in the latest release, so if you update to v2.1.0 it should now for your. If not, let me know!

**Comment by johngrasty** [comment]
That took care of it. Thanks.
