### ISSUE TITLE
Feature Request: “Save Without Formatting” command

### ISSUE THREAD

**Issue by smockle** [alexanderweiss/nova-prettier#56]
I typically use this extension with the “Format documents when saved” preference enabled. Occasionally, I’d like to save a document without formatting it using Prettier.

Could this extension add a “Save Without Formatting” option to Nova’s Command Palette?

Visual Studio Code [supports](https://github.com/microsoft/vscode/issues/38695#issuecomment-423422531) a “Save Without Formatting” command. I’m not sure it’d make sense to adopt the same keyboard [chord](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-rules) (<kbd>⌘</kbd><kbd>k</kbd> <kbd>s</kbd>), since I don’t see chords in Nova’s default keybindings, but adopting the same command name may aid discoverability (for folks who have used Visual Studio Code).

**Comment by alexanderweiss** [comment]
Sounds like a good idea! I'll look at this soon.

**Comment by alexanderweiss** [comment]
Sorry for the delay. It's out now in v2.2.0.

**Comment by smockle** [comment]
> Sorry for the delay. It's out now in v2.2.0.

Many thanks for adding this! It works great! 🎊
