### ISSUE TITLE
Working with NVM

### ISSUE THREAD

**Issue by ChrisBFusion** [alexanderweiss/nova-prettier#57]
The extension issues a dialog with the following text:

> Prettier couldn't be found because npm isn't available. Please make sure you have Node installed. If you've only installed Node through NVM, you'll need to change your shell configuration to work with Nova. See https://library.panic.com/nova/environment-variables/

The URL it points to isn't very helpful in providing a solution to the problem. What do I need to do exactly to get this extension working? I gather I need to enter something in my .zshrc but what?

**Comment by alexanderweiss** [comment]
There'll be something like the following in `~/.zshrc`. That needs to be in `~/.zprofile` or `~/.zlogin` instead so it's picked up by your login shell.

```
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
```

**Comment by ChrisBFusion** [comment]
Thank you!
