### ISSUE TITLE
Stopped formatting .twig files

### ISSUE THREAD

**Issue by petefazio** [alexanderweiss/nova-prettier#58]
Prettier stopped formatting .twig files. Maybe since latest update of prettier?

Panic Nova Build 221256
PLUGIN: Prettier Version 2.1.0
PLUGIN: TWIG Version 1.4.1 : Syntax Highlighting and Completions for Twig (and Craft CMS) Template Files (.twig)

**In the developer console, I see:**

Prettier[10:11:47.430000] Loading bundled prettier at /Users/xxxxxxxxxx/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier

Prettier[10:11:47.431000] Starting Prettier service

Prettier[10:11:50.093000] Formatting /templates/index.twig

Prettier[10:11:50.255000] No parser for /templates/index.twig

------

**If I try and do a workaround and use EDITOR > PRETTIER > FORMAT nothing happens and I get an error popup (attached) that says:**
"Prettier doesn't include a Parser for this file and no plugin is installed that does."
<img width="307" alt="Screen Shot 2020-12-03 at 10 01 42 AM" src="https://user-images.githubusercontent.com/19919953/101045808-8df07780-354e-11eb-8821-69bb356dde56.png">

Please help.

**Comment by alexanderweiss** [comment]
I don't think there's built-in support for Twig (see e.g. https://github.com/prettier/prettier/issues/5944), so unless you use a plugin like https://github.com/trivago/prettier-plugin-twig-melody I don't think it should try to format Twig files.

**Comment by petefazio** [comment]
Huh... I can't be crazy, I swear I was using it in conjunction with the TWIG craft plugin and I swear they were working together and my TWIG files were getting prettified. I'll try and get the melody plugin installed and see if that helps.

**Comment by claysondesign** [comment]
I thought this as well, but (and it is hacky) by adding prettier-plugin-twig-melody to the extension package https://github.com/alexanderweiss/nova-prettier/issues/44 does get twig formatting up and running and it works well thanks @alexanderweiss

**Comment by petefazio** [comment]
Thanks. I got it working. I used `npm install --dev prettier-plugin-twig-melody` in ~/Library/Application Support/Nova/Extensions/alexanderweiss.prettier and then added a couple dependencies (melody-idom and melody-runtime) and it seems to be working.
