### ISSUE TITLE
Cannot find module './parser-typescript' error

### ISSUE THREAD

**Issue by moonrise-tk** [alexanderweiss/nova-prettier#59]
Hello!

I get this error whenever I try formatting anything:

<img width="304" alt="Screen Shot 2020-12-09 at 11 51 23 AM" src="https://user-images.githubusercontent.com/31808124/101660345-11114200-3a15-11eb-9aa7-49c1583baa83.png">

Not sure what it means. I know I have a typescript parser installed.

<img width="482" alt="Screen Shot 2020-12-09 at 11 53 40 AM" src="https://user-images.githubusercontent.com/31808124/101660445-2f773d80-3a15-11eb-84a8-42742895cf5b.png">

**Comment by alexanderweiss** [comment]
You might want to try to clear node_modules and reinstall them. Seems like a file is missing that one of the modules is expecting.
I don't think @typescript-eslint has anything to do with it though.

**Comment by moonrise-tk** [comment]
You were right! Works now.
