### ISSUE TITLE
Not using local installation of prettier

### ISSUE THREAD

**Issue by alexanderflink** [alexanderweiss/nova-prettier#6]
I like to have prettier installed locally in my projects, but this extension seems to use it's own installation of prettier. In my project I have prettier 2.0.2 installed, but when running this extension it removes arrow function parenthesis which suggests to me it's using a version below 2.0.

I think the extension should run prettier locally installed in the project if available.

**Comment by alexanderflink** [comment]
I would suggest having something like this in `prettier.js` where it requires prettier to first check if it's locally available. However, I can't get the below code to work, it doesn't seem to find the prettier module even though I have checked the path is correct. Any ideas?

```js
		try {
			const prettier = require(nova.workspace.path +
				'/node_modules/prettier/standalone.js')
		} catch (err) {
			console.log(err)
		}
```

I noticed you are using the `nova-npm-executable` package. Correct me if i'm wrong, but isn't that only useful for running prettier executable using `npx`, not the js API?

**Comment by alexanderweiss** [comment]
Sorry for the delay. I'll see if I can make that work easily. You're also welcome to create a PR. Yeah, nova-npm-executable is not a perfect fit, but it's an easy way to install a module (I did want to the extension to be able to run standalone). I initially built the module into the extension, but that wasn't submittable back then, because file size limits for extensions were lower.

**Comment by alexanderweiss** [comment]
I've tried it out myself and Nova seems to limit what you can `require`. I'll see how well it works if I run things in a separate process.

**Comment by alexanderweiss** [comment]
Turns out `require`s have to be relative. Version 1.1.0 will now try to use the Prettier installed in your workspace root.
