### ISSUE TITLE
Prettier service exited with code 1

### ISSUE THREAD

**Issue by MeMattStone** [alexanderweiss/nova-prettier#60]
When I install Prettier via the Extensions Library I get a message box pop on the sidebar that says:

```
Prettier stopped running
Please report report an issue though Extension Library if this problem persists
```

In the debug console the following not very helpful errors show up:

```
Prettier[15:11:57.748000] Loading bundled prettier at /Users/mattstone/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier
Prettier[15:11:57.749000] Starting Prettier service
Prettier[15:11:57.962000] Prettier service exited with code 1
Prettier[15:11:57.962000] Starting Prettier service
Prettier[15:11:58.161000] Prettier service exited with code 1
```

I've tried uninstalling and re-adding the extension and disabled all other extensions to make sure there wasn't a conflict to no avail.

**Comment by paulburgess** [comment]
Just got a fresh Nova (trial) install and also seeing this as soon as adding the extension

**Comment by alexanderweiss** [comment]
Hmmm. That's problematic... There's some limitations in Nova that mean we can't read the error logs of the process crashing (as far as I'm aware at least). Could you (@MeMattStone and/or @paulburgess) try the following to get some more info:

1. Go to the extension library
2. Right click the Prettier extension and then Show in Finder
3. Open that folder in Terminal
4. Run `/usr/bin/env node Scripts/prettier-service/prettier-service.js ../../node_modules/prettier`
5. Report the output.

If everything's alright it should say:
```
Content-Length: 37

{"jsonrpc":"2.0","method":"didStart"}
```
But in your case you'll probably get some error.


Sorry for the delay by the way.

**Comment by MeMattStone** [comment]
Here is the output I get:

```
/Users/mattstone/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/third-party.js:9863
      for await (const place of this.config.searchPlaces) {
          ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mattstone/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/node_modules/prettier/index.js:16652:18)
```

**Comment by alexanderweiss** [comment]
Aha! I'm guessing your node doesn't support some of the syntax/language features the extension uses. What version of node are you using (`/usr/bin/env node -v`)? And are you using nvm? I need to document minimum requirements / add a check for older node versions...

**Comment by MeMattStone** [comment]
Ah ok, that makes sense. Looks like my default is set to v.8.17.0 (not sure if that's the default for Big Sur or if I've inadvertently changed it at some point) and yes I use nvm.

```
nvm ls                                                                                                                                                                                                           
         v8.0.0
->      v8.17.0
        v12.9.0
       v12.16.2
        v13.6.0
        v14.6.0
        v15.0.0
         system
default -> v8.17.0
node -> stable (-> v15.0.0) (default)
stable -> 15.0 (-> v15.0.0) (default)
iojs -> N/A (default)
unstable -> N/A (default)
lts/* -> lts/fermium (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0
lts/dubnium -> v10.23.0 (-> N/A)
lts/erbium -> v12.20.0 (-> N/A)
lts/fermium -> v14.15.2 (-> N/A)
```

**Comment by paulburgess** [comment]
I got the same output as Matt did here/above: https://github.com/alexanderweiss/nova-prettier/issues/60#issuecomment-754140935

I'm running node v8.11.1 - will updating that help here?

Many thanks!

**Comment by paulburgess** [comment]
Updated to latest version of node and all running fine now

**Comment by alexanderweiss** [comment]
Great! @MeMattStone, if it doesn't work after updating and you also have node installed outside of nvm it could also be that non-nvm node you have to update.

**Comment by MeMattStone** [comment]
I set the latest version of node as my default in nvm and now working fine after restarting nova

**Comment by alexanderweiss** [comment]
Perfect!
