### ISSUE TITLE
Error while formatting with prettier-svelte-plugin

### ISSUE THREAD

**Issue by danielsneijers** [alexanderweiss/nova-prettier#61]
I got this error after installing the "prettier-plugin-svelte" plugin:
<img width="303" alt="Screenshot 2020-12-23 at 13 00 01" src="https://user-images.githubusercontent.com/1942473/102994171-d6340180-451e-11eb-8c7d-50262a62762b.png">

I have both prettier and the svelte plugin installed locally in my project and running it from the command line seems to work with the following config:

```json
{
  "tabWidth": 2,
  "semi": true,
  "trailingComma": "es5",
  "plugins": ["prettier-plugin-svelte"]
}

```

Also verified that the plugin folder is in my node_modules folder (and tried clearing and reinstalling for good measure) but am kind of lost where to look next. Any clue how to fix this? Happy to help debugging.

**Comment by alexanderweiss** [comment]
Are you using `nvm` by any chance? With different defaults and project versions? If you've reinstalled `node_modules` already I'm not really sure what this could be to be entirely honest..

**Comment by danielsneijers** [comment]
Yes I am using NVM, does that affect the plugin? I'm looking at the Nova preferences and I do have "automatically request environment from login shell" turned on, it includes the path to the NVM/node directories

**Comment by alexanderweiss** [comment]
I could imagine the default node version in `nvm` is different from the one that your project uses? In that case the require logic of Prettier might expect stuff to be different than how it's installed maybe. Just speculating here. Maybe try setting your project's node version to be the default node version in `nvm`.

**Comment by alexanderweiss** [comment]
Closing this. If you're having issues this, let me know!
