### ISSUE TITLE
Intermittent "can't find npm and prettier" message

### ISSUE THREAD

**Issue by belcar-s** [alexanderweiss/nova-prettier#62]
Sometimes upon opening Nova, I am greeted with the following notification:
![Screen Shot 2021-01-09 at 12 13 43](https://user-images.githubusercontent.com/73370025/104104175-75256100-5274-11eb-8d6b-416da216bf0b.png)

When this happens, no files are formatted on save or through the format command.

I am certain npm is installed, and this issue often goes away after one or more Nova restarts. I do not see any output in the Extension Console.

I apologize I can't give more information in the issue because I'm not certain of what exactly can be helpful. Please ask any questions you may have. Many thanks for the extension!

**Comment by alexanderweiss** [comment]
Oh wow... I hadn't heard about that yet. If it happens can you try disabling and re-enabling the extension in the Extension Library without restarting Nova. I'd be interested to hear if it would then still occur. I might try adding some retry behaviour in that case.

**Comment by belcar-s** [comment]
I tried, and it did not!

**Comment by alexanderweiss** [comment]
I've released v2.2.0 that will retry loading Prettier. Let me know if that resolves it for you!
