### ISSUE TITLE
Markdown table with nested code with vertical bar bug

### ISSUE THREAD

**Issue by jasonroyle** [alexanderweiss/nova-prettier#63]
Nova v4.2 (236512)
Nova Prettier v2.1.0

When the vertical bar character is used in code which is nested in a table the vertical bar is interpreted as a table column delimiter and results in the following.

This:

```markdown
| Foo | Bar |
| --- | --- |
| `foo: string | string[]` | `bar` |
```

Formats to this:

```markdown
| Foo          | Bar       |
| ------------ | --------- | ----- |
| `foo: string | string[]` | `bar` |
```

**Comment by alexanderweiss** [comment]
This is an issue with prettier I'm afraid. The same happens in [the playground]( https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABAMQhdGBCAhgE54A6UGAtDXujVeZegAYBmOS6AzjMQJZQA5nV4DhAbQC6LOiwBGJWahAAaEBAAOMftG7JQJYhADuABRIJ9KQgBsThAJ77184oTABrODADKmj0EhZD4AVzh1OABbeTgAEzj4gBlCYVDCIThsYijCGB1hZBBCUJgINRAACxgo2wB1Sv54bgCwOF8rJv4ANybHIrBuFxBBbjhiGDN3IVzkNjsx9QArbgAPfHcvH19CKLgkwTg5hYiQFdXfINs4AEVQiHhj20WQAOIx4iLc4k840ygKppxDA6vw4jBKsgABwABnUQIgYzq7k0RSBcA+3SO6gAjvd4FMtNZitwqFA4PF4hViHA8fwaVMMrMkPNnqcxlF+CFiOF1Nwrrd8UcWSd1DBCPJQeDIUgAExi9z8WxBADCECizJAGIArBVQmMACoS6ysl7dcIASSgiVgvjAAm0AEFrb4YI5rk8xgBfL1AA). You should probably check out the prettier issues and maybe create one there.

**Comment by jasonroyle** [comment]
Thanks @alexanderweiss, for transparency I have created [this issue](https://github.com/prettier/prettier/issues/10164) over on the prettier repository.
