### ISSUE TITLE
Extension not formatting via command or on save

### ISSUE THREAD

**Issue by michaelaflores** [alexanderweiss/nova-prettier#64]
For some reason the extension has stopped formatting when using the menu bar command or when saving my file, on files it used to be able to operate on (`.tsx` files). The only logs for this extension in the extension console are:
```
Prettier[17:29:17.335000] Loading project prettier at /Users/michaelflores/workspace/video-client/node_modules/prettier

Prettier[17:29:17.336000] Starting Prettier service
```

Nothing appears in the console after attempting to format the file. Is there a way to debug this better?

**Comment by alexanderweiss** [comment]
Could you try disabling and re-enabling the extension (without restarting Nova). If that doesn't work, could you try the following:

1. Go to the extension library
2. Right click the Prettier extension and then Show in Finder
3. Open that folder in Terminal
4. Run `/usr/bin/env node Scripts/prettier-service/prettier-service.js ../../node_modules/prettier`
5. Report the output.

If everything's alright it should say:
```
Content-Length: 37

{"jsonrpc":"2.0","method":"didStart"}
```

That would help pinpointing the problem.

**Comment by michaelaflores** [comment]
@alexanderweiss I have tried disabling and re-enabling the extension without restarting Nova, to no avail. 

I wasn't sure if this command should be run inside the `Extensions` folder or inside `alexanderweiss.prettier` but ran it in both just in case, as both returned `MODULE_NOT_FOUND` errors. 
```
michaelflores@Michaels-iMac alexanderweiss.prettier % /usr/bin/env node Scripts/prettier-service/prettier-service.js ../../node_modules/prettier
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module '../../node_modules/prettier'
Require stack:
- /Users/michaelflores/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/prettier-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at new PrettierService (/Users/michaelflores/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/prettier-service.js:11:19)
    at Object.<anonymous> (/Users/michaelflores/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/prettier-service.js:87:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/michaelflores/Library/Application Support/Nova/Extensions/alexanderweiss.prettier/Scripts/prettier-service/prettier-service.js'
  ]
}
michaelflores@Michaels-iMac alexanderweiss.prettier % cd ..
michaelflores@Michaels-iMac Extensions % /usr/bin/env node Scripts/prettier-service/prettier-service.js ../../node_modules/prettier
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module '/Users/michaelflores/Library/Application Support/Nova/Extensions/Scripts/prettier-service/prettier-service.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by alexanderweiss** [comment]
I'm sorry, I forgot you were using your project's Prettier. It should've been (assuming Prettier is still installed in that project at at that location):

`/usr/bin/env node Scripts/prettier-service/prettier-service.js /Users/michaelflores/workspace/video-client/node_modules/prettier`

You should run it inside the `alexanderweiss.prettier` folder.

**Comment by michaelaflores** [comment]
@alexanderweiss ah gotcha, here's the results from that:
```
michaelflores@Michaels-iMac alexanderweiss.prettier % /usr/bin/env node Scripts/prettier-service/prettier-service.js /Users/michaelflores/workspace/video-client/node_modules/prettier
Content-Length: 37

{"jsonrpc":"2.0","method":"didStart"}
```

**Comment by michrome** [comment]
Hey @michaelaflores @alexanderweiss did you solve this? Also stopped working for me this week. The extension _is_ running but all indentation is being stripped out.

e.g. This:

```js
export default function
Page(      { content }) {
                return <>{content}</>
}

```

gets "Prettiered" to:

```js
export default function Page({ content }) {
return <>{content}</>
}

```

And this:

```html
<html><h1>Mike</h1><ul><li>Mike</li></ul>
</html>
```

gets "Prettiered" to:

```html
<html>
<h1>Mike</h1>
<ul>
<li>Mike</li>
</ul>
</html>

```

I've tried reinstalling the extension and updating to latest Nova 4.3.

```bash
mike@MacBook alexanderweiss.prettier % /usr/bin/env node Scripts/prettier-service/prettier-service.js /Users/mikejerome/code/j4e-name/node_modules/prettier
Content-Length: 37

{"jsonrpc":"2.0","method":"didStart"}
```

**Comment by michrome** [comment]
Update: solved my issue. While exploring Nova's Project Settings UI, I must have inadvertently created a `.nova/Configuration.json` in my project's root that set the tab width to 0. 🤦

```json
{
  "prettier.default-config.tabWidth" : 0,
  "workspace.preview_type" : "custom"
}
```

**Comment by alexanderweiss** [comment]
Great @michrome!
@michaelaflores Hmmm. Have you changed the 'Ignore documents without Prettier configuration file' or 'Ignore remote documents' settings by any chance? (Either in the extension preferences or the project settings) If not, I'll see about adding some additional logging and releasing a new version asap so we might get some more info.

**Comment by michaelaflores** [comment]
@alexanderweiss I've tried using this extension on a new computer/Nova install and it works correctly, so I believe this issue was specific to my previous machine/an errant setting change as you suggest. Closing this, thanks for your help!
