### ISSUE TITLE
CSFixer in nova-prettier

### ISSUE THREAD

**Issue by creativecat** [alexanderweiss/nova-prettier#65]
Not a bug, but a enhancement feature/ question. Can I add CSFixer to nova-prettier plugin?
I found that [plugin](https://gist.github.com/Billz95/9d5fad3af728b88540fa831b73261733), but my skills in that case are not pretty good ...
I'm happy getting prettier and your plugin for Nova installed on my Mac. But I don't see how to use CSFixer with Prettier ...
Thank you :-)

**Comment by alexanderweiss** [comment]
Hey! I think you're looking for a PHP-CS-Fixer extension. That will / could allow you to then use Prettier. I don't think the other way around would work since it's PHP-CS-Fixer that loads Prettier and not the other way around.
