### ISSUE TITLE
fast-diff not that fast in large files

### ISSUE THREAD

**Issue by biati-digital** [alexanderweiss/nova-prettier#66]
**fast-diff** seems to be not that fast on large files, it may take several seconds until Nova shows a warning asking you if you want to wait until the extension finishes the process or disable it. In the latest version of Nova it seems that Nova is capable of restoring cursors and selections without this code after formatting.

This code should not be required anymore.
https://github.com/alexanderweiss/nova-prettier/blob/df11b02889e45f438270b5ecbece26d9fe03fbc8/src/Scripts/formatter.js#L279-L294

Also this line should be removed
https://github.com/alexanderweiss/nova-prettier/blob/df11b02889e45f438270b5ecbece26d9fe03fbc8/src/Scripts/formatter.js#L380

Removing that code should improve the formatting speed on large files.

**Comment by alexanderweiss** [comment]
Thanks for letting me know! No, it wasn't very fast on complex files, but it was a lot faster than what was built into Prettier. Interesting, I didn't see this in any release notes. I guess it may have been added even still during the betas.

**Comment by alexanderweiss** [comment]
v2.2.1 should be faster on files with many changes then!

**Comment by biati-digital** [comment]
Well, ignore my previous comment, I did a few tests removing the code I mentioned and the cursors and selections were restored correctly every single time, now it stopped working, they are restored but not in the correct position. I've no idea what happened, anyway, fast-diff still will cause problems with large files. I'll try to figure out what was I doing when it worked.

**Comment by alexanderweiss** [comment]
Yeah, on trying some more I noticed it's not quite alright. It has a tendency to move one or more characters. I feel like that should be reported as a bug to Panic though.

I have actually already released a version without any explicit cursor restoration.

**Comment by biati-digital** [comment]
I was doing the same, removing all the cursor restoration. Yes I think we should report this to Panic.

In case they take ages to respond or fix this, I was thinking in another way we could "fix" this:
(Just and idea, have not done it yet but wanted to know what you think.)

We store the initial position of selections before changing the editor content: 
```javascript
for (const selection of editor.selectedRanges) {
     // selection start is the first position of a cursor or selection
     const start = selection.start; //output 709
}
```
![CleanShot 2021-02-21 at 15 09 26](https://user-images.githubusercontent.com/1219228/108638854-ef8df700-7456-11eb-83d7-3581e45106d7.png)


Then after changing the editor content
```javascript
await editor.edit((e) => {
    e.replace(documentRange, formatted);
});
        
editor.selectToBeginningOfWord();

// Get the new selections position
for (const selection of editor.selectedRanges) {

     // now the start is 707, the selection was moved but now we know that
     // the selection was moved 2 places,
     const start = selection.start; 
}
```
![CleanShot 2021-02-21 at 15 09 53](https://user-images.githubusercontent.com/1219228/108638857-f3217e00-7456-11eb-989e-cba5a61df0e3.png)


Here you can see that the selection was moved but now we know that before formatting the first selection start was 709, after formatting, the new selection was 707, it moved 2 places, the same two letters that are selected. We could then loop the selections and adjust the start and end by removing the difference, so in this example the first selection should actually start at 705

There's probably more scenarios that I'm not considering, do you think this have a chance to work?

**Comment by alexanderweiss** [comment]
Well, for formatting the cursor moving is expected. Which is why you need the diffing. Knowing that Nova probably places it almost correctly would allow some quick, hacky adjustments. But I'd prefer them just looking at it or keeping proper diffing than that I think.

**Comment by biati-digital** [comment]
Yes, after formatting, the cursors will move but it will be great to maintain the cursor in the same place it was before the formatting. It's probably a waste of time trying to "fix" this. I'll report it as a bug to Panic.

**Comment by alexanderweiss** [comment]
@biati-digital did you ever hear back about the cursor issues from Panic?

**Comment by biati-digital** [comment]
@alexanderweiss No, since February I've sent 6 emails mentioning different issues including this one, only received reply of 2 emails after almost two months. 

The other options is the forum [https://devforum.nova.app](https://devforum.nova.app) not sure If they are active in there.
