### ISSUE TITLE
Prettier is crashing every time I open a document

### ISSUE THREAD

**Issue by sphelan15** [alexanderweiss/nova-prettier#67]
Every time I open a document, I get a message that Prettier has stopped working.  Clicking Restart just caused it to do the same thing again.  See attached screenshot.

![Screen Shot 2021-02-23 at 2 05 08 PM](https://user-images.githubusercontent.com/79539462/108894444-496df880-75e0-11eb-87b9-586cfb870262.png)

**Comment by alexanderweiss** [comment]
That's too bad. Can you go into Preferences > General and enable the `Show development items...` option and then enable Show Extension Console under Extensions in the menu bar.

This should say something like:
```
Prettier[20:14:25.332000] Loading project prettier at /Users/Alexander/someproject/node_modules/prettier
Prettier[20:14:25.332000] Starting Prettier service
```

If it says something else, could you post it here?

If it does, can you try running the Prettier process directly and let me know what the output is. You can do it by following these steps:

1. Go to the extension library
2. Right click the Prettier extension and then Show in Finder
3. Open that folder (called `alexanderweiss.prettier`) in Terminal
4. Run `/usr/bin/env node Scripts/prettier-service/prettier-service.js <path-to-prettier-logged-in-extension-console>` (put the path logged in the Extension Console where placeholder is)
5. Report the output.

If everything's alright it should say:
```
Content-Length: 37

{"jsonrpc":"2.0","method":"didStart"}
```

But I'm guessing it'll say something else. In any case it would help pinpointing the problem.

**Comment by sphelan15** [comment]
There were errors in both scenarios you asked me to try...see attached:

![Screen Shot 2021-02-23 at 2 27 24 PM](https://user-images.githubusercontent.com/79539462/108897286-f007c880-75e3-11eb-9ef6-adccdef173d9.png)

![Screen Shot 2021-02-23 at 2 31 35 PM](https://user-images.githubusercontent.com/79539462/108897302-f5651300-75e3-11eb-8a99-8b480fa056b2.png)

**Comment by alexanderweiss** [comment]
Seems like you have an unsupported Node version. Prettier requires at least 10.13.0 (or maybe newer now). Could you try updating your Node (or `nvm`'s default Node version if you use it) to the latest (or at least 10.13.0).
