### ISSUE TITLE
Extension activated on wrong syntax

### ISSUE THREAD

**Issue by tomy0000000** [alexanderweiss/nova-prettier#71]
I'm constantly seeing prettier try to format `.py` in the debug menu as follow

![截圖 2021-05-05 下午1 50 11](https://user-images.githubusercontent.com/23290356/117101505-f1562e00-ada8-11eb-8ba0-88d1cf7f4d38.png)

It seems to be a duplicate of #25, it just that it does not report the error with a notification in the latest version (v2.2.1).

Maybe there should be a syntax check before dispatching format?

**Comment by alexanderweiss** [comment]
Yes, that's because Prettier knows what extensions are and are not available. It should be super fast though. Is it a problem for you? It could ignore files for which a parser wasn't available the first time, but then if you install a plugin you'll need to re-open the project in Nova.

**Comment by tomy0000000** [comment]
I wonder if that's gonna affect other extension from working properly, although that's just my own speculation.

**Comment by alexanderweiss** [comment]
No, I wouldn't know why. Every extension gets several seconds on save to make edits. And this extension won't make any if it sees a file shouldn't be formatted. So should be fine!

**Comment by tomy0000000** [comment]
I've just made some tunning to my extensions, it won't have too many interference now. I'll open another issue if any problem arise.
