### ISSUE TITLE
Prettier saves are losing scroll state

### ISSUE THREAD

**Issue by unsoluble** [alexanderweiss/nova-prettier#72]
After the Nova 6.2 update, every time I save a file that results in Prettier change to the formatting, it dumps my view back to Line 1 of the file. I'm 99% sure it didn't do this prior to 6.2 — it used to maintain my scroll state. Is this something misconfigured on my end?

**Comment by alexanderweiss** [comment]
I just released v2.2.2 that reverts the removal of diffing / cursor restoration in the extension that fixes this as well as for me. Let me know if it doesn't.
