### ISSUE TITLE
Prettier not respecting syntax indentation settings

### ISSUE THREAD

**Issue by donileo** [alexanderweiss/nova-prettier#74]
Prettier version: 2.3.0
Nova version: 6.2

For some reason I can't get prettier to format a json file using 2 spaces. I have 2 spaces set as the global default in the extension setting but when I hit format on save it goes and uses 4 spaces. I did verify it is running. It just isn't respecting what I put in the extension setting preferences or if I set two spaces on the bottom panel of Nova (next to syntax).

**Comment by alexanderweiss** [comment]
Do you have a `.prettierrc` or `.editorconfig` file in the same folder as the file or in any parent folder? Those will take precedence over the defaults you set in Nova. Also, if you have a project open (the sidebar on the left will show files), do you maybe have 4 spaces configured in the project settings?

**Comment by donileo** [comment]
No I don't have any project settings where the file is. There isn't any .prettierrc or .editorconfig file there either.

**Comment by alexanderweiss** [comment]
I don't think Nova will do it. The extensions definitely doesn't (and I don't think Prettier itself would). Great that you found it!
