### ISSUE TITLE
ts, json, jsx, and tsx support

### ISSUE THREAD

**Issue by jefflewis** [alexanderweiss/nova-prettier#8]
Prettier can handle lots of file types. I'd like them all to be supported, even if that means having a short default list and a setting to set to a custom list.

**Comment by alexanderweiss** [comment]
Are you referring to the `Format with Prettier` menu item or is it not working at all in those file types for you? It should. It's supposed to work for the following types:
```
[
	"json",
	"html",
	"javascript",
	"jsx",
	"flow",
	"typescript",
	"vue",
	"angular",
	"less",
	"scss",
	"graphql",
	"markdown",
	"yaml"
]
```

Something might be broken there... Or Panic may have changed the names. I'll look into it.

**Comment by jefflewis** [comment]
I'm not sure what the disconnect was. This does appear to be working now.

**Comment by alexanderweiss** [comment]
Awesome. Sorry for the delay by the way (notification settings were wrong...)

**Comment by tmayr** [comment]
I'm gonna comment here but I'm not getting any formatting on `ts` files on the last public version, build 202519
