### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by yabdab** [alexanderweiss/nova-prettier#88]
There has not been an update in almost a year and it has so many things going wrong with it.

**Comment by Rocketpilot** [comment]
Open pull request from the middle of last year isn't a promising sign. Overall I'm concerned by the health of the Nova extension ecosystem.

**Comment by alexanderweiss** [comment]
I only rarely use it myself at the moment so I haven't been doing much with it. I try to check out issues once in a while. But it's been a long time now. Will see if I have some time soon. Contributions are welcome though.

**Comment by guillermo-avalos** [comment]
It's such a shame, Nova is a very nice editor. I wish @alexanderweiss had a bit more time fixing some of the issues, mainly the syntax coloring problem.

**Comment by alexanderweiss** [comment]
What's the syntax colouring problem?

**Comment by guillermo-avalos** [comment]
The entire code would be randomly colorized. I've stopped using Nova about a year ago, sadly. Can't be very optimistic about its future.

**Comment by alexanderweiss** [comment]
I'll close this now then. If you do still use Nova, please feel free open an issue for any problems. Preferably with clear steps to reproduce.
