### ISSUE TITLE
Option to use the project `.prettierrc`

### ISSUE THREAD

**Issue by idrakimuhamad** [alexanderweiss/nova-prettier#9]
It seems the nova’s prettier right now uses whatever default config that it came with instead of using the config from `.prettierrc` in project root and using local copy of prettier. Any plan to have this soon?

Thanks.

**Comment by alexanderweiss** [comment]
This extension uses Prettier's built-in config resolution. So it should work just like any other Prettier installation and pick up on your .prettierrc file. It does currently cache it though. So once you open a file it won't update the config for that file until you've relaunched Nova. That might be what you're running into? I'll look into improving that.
