### ISSUE TITLE
Format command doesn't work under a very simple set of circumstances, described in the issue

### ISSUE THREAD

**Issue by belcar-s** [alexanderweiss/nova-prettier#90]
I've found that the format command doesn't do anything if…
- …the _Ignore projects without Prettier configuration file_ option is enabled,
- and the current project doesn't have a Prettier configuration file.

I would love to be able to manually format a file with Prettier, even if I want formatting-on-save to be, by default, exclusive to projects with Prettier configuration files.

Thanks.

**Comment by alexanderweiss** [comment]
Next release will fix this 😃
