### ISSUE TITLE
Under what license is the extension code licensed?

### ISSUE THREAD

**Issue by reykjalin** [alexanderweiss/nova-prettier#93]
I'd like to lift some of the code from the extension to use for "format on save" functionality in [my PHP_CodeSniffer extension](https://git.sr.ht/~reykjalin/nova-phpcs) but I'm not sure if that's something you're open to given that the repo doesn't include a license file.

Is it all right to copy and use your code (given attribution of course)? Did you have a specific license in mind for the extension?

Just in case you want to add a license but don't know where to start I find [Choose A License](https://choosealicense.com) by GitHub to be a helpful resource.

**Comment by alexanderweiss** [comment]
I'll add the MIT license :)
